### ISSUE TITLE
What's the difference between the two directories?

### ISSUE THREAD

**Issue by pruhstal** [thebillkidy/MERGE-Stack#2]
I'm a bit confused on why there are 2 separate directories with very similar structure for both SQL and GRAPHQL.

There's quite a bit of duplication between the two, so I'm just trying to wrap my head around the reasoning between them. 

Do I choose which one I want to use for my project? Why would I choose one over the other?

Thanks!

**Comment by XavierGeerinck** [comment]
Hi! 

The difference between the SQL folder and the GRAPH folder is the database engine being used. In the first a relational database is being used, while in the second a graph database engine (Neo4j) is being used. 

The reason this was done is to explore the usability of this stack over the different database engines to find a decoupled way of working and easy interchanging of the database engine. 

Please let me know if this answers your question :)

**Comment by XavierGeerinck** [comment]
See #3 for the same info :)
